# deployment:
# API version 1 에 속함
apiVersion: apps/v1
kind: Deployment

# metadata :
# deployment의 이름을 정해야 함
metadata:
  name: joisfe-2

# spec :
spec:
  # deployment가 자신의 관리 대상을 결정하는
  # label selector 정의
  # app label을 사용, label은 임의의 key-value 쌍
  selector:
    matchLabels:
      app: joisfe-2

  # template :
  # deployment가 pod를 만들 때 쓰임
  template:
    # deployment 정의 속 pod 정의에는 이름이 없음
    # 그 대신 label selector와 일치하는 label을 지정
    metadata:
      labels:
        app: joisfe-2

    # spec :
    # pod의 정의에는 container name과 image name을 지정
    spec:
      containers:
        - name: web
          image: kiamol/ch02-hello-kiamol